#!/bin/sh
# Copyright (c) 2001, Justin Simms, justins@dnai.com
#
# Permission is hereby granted, free of charge, to any person obtaining a 
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the 
# Software is furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# traplogger version 1.0 - file "trapmon"

# example Linux init startup file - you'll probably want to customize this!
# in any case make sure the directory /var/log/trapmon exits if you use as-is
# and make sure trapmon and snmptrapd are both in root's path
# (which you can define in this file... for example PATH=/usr/local/bin)

LOGDIR=/var/log/trapmond
PATH=$PATH:/usr/local/bin
case $1 in
    'start')
	echo "Starting traplogger, logging to $LOGDIR..."
	trapmond $LOGDIR &
	;;
    'stop')
	echo "Stopping traplogger (killing snmptrapd)..."
	pkill snmptrapd
	;;
esac
